### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by orefalo** [mowtwo/svelte-tree#2]
Hi Friend, nice job!

I am planning to implement a similar component with the following features (via UI interactions and API)

events for every action
Expand/collapse/toggle node(s)
Enable/Disable node(s)
find by text
find by uid
get current selected node(s)
for selection of node(s)
insertAfter
insertBefore
remove
focus
auto scroll the parent container
checkbox selection
drag&drop
isDraggable Validation
isDroppable Validation
multiple instances per page
keyboard navigation
theming
edit in place
filtering
sorting by text, sort by Fn
lazy loading
Expand to element
Expland to path

I couldn't find such component in the svelte world.
So I am planning to port https://github.com/amsik/liquor-tree which has most of it.

What is your plan?

**Comment by mowtwo** [comment]
Thank you very much for your attention! 

So sad this is just a svelte2web-components demo, the earliest we did't make a perfect plan, so will not continue to update. Also We are very much looking forward to the development of your project.  If there is anything you can use, hope that will help you.😄😄

**Comment by orefalo** [comment]
Hi, thank you.
Didn't start just yet
Have a few other pieces to put together 
Will most likely begin in early July

Will call for help

I will surely need it
